#!/usr/bin/env python3
"""Сборка js/site-data.js для главной страницы отчёта.

Тянет живые цифры из data/exports (API 2026-09-27), вики-экспортов и
webmaster/parsed_data.json. Все KPI и графики главной — только отсюда.

Запуск из корня проекта: python scripts/export/build_site_data.py
"""
import csv
import json
import os
import sys
from collections import defaultdict

sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
WM_API = os.path.join(ROOT, "data", "exports", "yandex_webmaster", "2026-09-27")
MT_API = os.path.join(ROOT, "data", "exports", "metrica", "2026-09-27")
WM_WIKI = os.path.join(ROOT, "brain", "wiki", "webmaster_analytics", "exports")
MT_WIKI = os.path.join(ROOT, "brain", "wiki", "metrika_analytics", "exports")
OUT = os.path.join(ROOT, "reports", "cifra18-audit", "js", "site-data.js")


def jload(p):
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def cload(p):
    with open(p, encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


summary = jload(os.path.join(WM_API, "summary.json"))
insearch = jload(os.path.join(WM_API, "insearch_history.json")).get("history", [])
popular = jload(os.path.join(WM_API, "queries_popular.json"))
eco = jload(os.path.join(MT_API, "ecommerce.json")).get("data", [])
goals = jload(os.path.join(MT_API, "goals.json")).get("goals", [])
metsum = jload(os.path.join(MT_WIKI, "metrika_summary.json"))
parsed = jload(os.path.join(ROOT, "webmaster", "parsed_data.json"))

# В поиске по месяцам (последнее значение месяца)
bym = {}
for p in insearch:
    bym[p["date"][:7]] = p["value"]
insearch_monthly = [{"m": k, "v": v} for k, v in sorted(bym.items())]

# Выручка
purch = rev = 0
topdays = []
for r in eco:
    m = r.get("metrics", [0, 0])
    p, v = (m[0] if len(m) > 0 else 0), (m[1] if len(m) > 1 else 0)
    purch += p
    rev += v
    if v:
        topdays.append({"d": r["dimensions"][0]["name"], "v": round(v), "p": p})
topdays.sort(key=lambda x: -x["v"])

# Источники за год (API, англ. метки -> короткие русские)
SMAP = {"Search engine traffic": "Поиск", "Internal traffic": "Внутренние",
        "Direct traffic": "Прямые", "Social network traffic": "Соцсети",
        "Link traffic": "Ссылки", "Messenger traffic": "Мессенджеры",
        "Cached page traffic": "Кэш", "Recommendation system traffic": "Рекомендации"}
src = defaultdict(int)
for r in jload(os.path.join(MT_API, "sources_summary.json")).get("data", []):
    dims = r.get("dimensions", [])
    m = r.get("metrics", [])
    if len(dims) > 1 and m:
        src[SMAP.get(dims[1].get("name", "?"), dims[1].get("name", "?"))] += m[0]
sources = sorted(({"s": k, "v": int(v)} for k, v in src.items()),
                 key=lambda x: -x["v"])

SITE = {
    "generated": "2026-09-27",
    "searchable": summary.get("searchable_pages_count", 0),
    "excluded": summary.get("excluded_pages_count", 0),
    "sqi": summary.get("sqi", 0),
    "statuses": parsed.get("stats", {}).get("status_counts", {}),
    "insearchMonthly": insearch_monthly,
    "insearchFirst": insearch_monthly[0] if insearch_monthly else None,
    "insearchLast": insearch_monthly[-1] if insearch_monthly else None,
    "popularCount": popular.get("count", 0),
    "popularWeek": "%s — %s" % (popular.get("date_from", "")[5:],
                                popular.get("date_to", "")[5:]),
    "popularTop10": [q["query_text"] for q in popular.get("queries", [])[:10]],
    "purchases": purch,
    "revenue": round(rev),
    "revenueTop5": topdays[:5],
    "goalsActive": sum(1 for g in goals if g.get("status") == "Active"),
    "metrikaVisits": metsum.get("visits_total", 0),
    "metrikaSearchShare": 4.22,
    "sourcesYear": sources,
}

with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* Generated by scripts/export/build_site_data.py. Do not edit by hand. */\n")
    f.write("const SITE = ")
    json.dump(SITE, f, ensure_ascii=False)
    f.write(";\n")

print("Wrote %s" % OUT)
print("searchable=%s sqi=%s revenue=%s purchases=%s popular=%s" % (
    SITE["searchable"], SITE["sqi"], SITE["revenue"],
    SITE["purchases"], SITE["popularCount"]))
